CREATE TABLE "donasi" (
  "id" int PRIMARY KEY,
  "kategori" varchar,
  "content" text,
  "title" varchar,
  "tanggal_awal" date,
  "tanggal_akhir" varchar,
  "target" decimal,
  "terkumpul" decimal
);

CREATE TABLE "donatur" (
  "id" int PRIMARY KEY,
  "nama_donatur" varchar
);

CREATE TABLE "donasi_relasi" (
  "id" int PRIMARY KEY,
  "program_id" int,
  "donatur_id" int,
  "jumlah_donasi" decimal,
  "method" varchar
);

CREATE TABLE "histori" (
  "id" int PRIMARY KEY,
  "donatur_id" int,
  "total" decimal,
  "date" date,
  "status" varchar
);

CREATE TABLE "program" (
  "id" int PRIMARY KEY,
  "title" varchar(255),
  "content" varchar,
  "collected_donation" int,
  "donation_target" int,
  "start_date" date,
  "end_date" date,
  "remaining_days" int,
  "category" varchar(100),
  "image" varchar(255)
);

CREATE TABLE "donation" (
  "id" int PRIMARY KEY,
  "campaign_id" int,
  "donor_id" int,
  "amount" int
);

CREATE TABLE "donor" (
  "id" int,
  "name" varchar(100),
  "email" varchar(100),
  "phone_number" varchar(20)
);

CREATE TABLE "history" (
  "id" int,
  "campaign_id" int,
  "donation_date" date,
  "description" varchar(100)
);

CREATE TABLE "zakat_campaigns" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar,
  "content" text,
  "collected_amount" decimal,
  "target_amount" decimal,
  "start_date" date,
  "category" varchar,
  "image" varchar
);

CREATE TABLE "donations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "campaign_id" int,
  "donor_id" int,
  "amount" decimal
);

CREATE TABLE "donors" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "email" varchar,
  "phone_number" varchar
);

CREATE TABLE "donation_history" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "campaign_id" int,
  "donation_date" date,
  "description" text
);

CREATE TABLE "donation_program" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "program_name" varchar,
  "category" varchar,
  "end_date" date,
  "total_collected" bigint,
  "target_amount" bigint,
  "description" text
);

CREATE TABLE "partner" (
  "id" varchar PRIMARY KEY,
  "partner_name" varchar
);

CREATE TABLE "program_partner" (
  "program_id" int,
  "partner_id" varchar
);

CREATE TABLE "article" (
  "id" varchar PRIMARY KEY,
  "title" text,
  "date" date,
  "time" time,
  "content" text,
  "category_id" varchar
);

CREATE TABLE "article_category" (
  "id" varchar PRIMARY KEY,
  "category_name" varchar
);

CREATE TABLE "program_article" (
  "program_id" int,
  "article_id" varchar
);

CREATE TABLE "testimonial" (
  "id" varchar PRIMARY KEY,
  "name" varchar,
  "date" date,
  "time" time,
  "content" text,
  "type_id" varchar,
  "program_id" varchar
);

CREATE TABLE "testimonial_type" (
  "id" varchar PRIMARY KEY,
  "type_name" varchar
);

CREATE TABLE "testimonial_program" (
  "id" varchar PRIMARY KEY,
  "program_name" varchar
);

CREATE TABLE "qurban_program" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" "VARCHAR(255)",
  "context" TEXT,
  "image_url" "VARCHAR(255)",
  "video_url" "VARCHAR(255)",
  "status" "ENUM(active,expired,draft)",
  "created_at" "DATETIME",
  "updated_at" "DATETIME"
);

CREATE TABLE "qurban_target" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "program_id" INT,
  "target_mustahik" INT,
  "target_lokasi" INT,
  "target_pequrban" INT
);

CREATE TABLE "qurban_stats" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "program_id" INT,
  "jumlah_pequrban" INT,
  "total_donasi" BIGINT,
  "target_donasi" BIGINT
);

CREATE TABLE "qurban_gallery" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "program_id" INT,
  "image_url" "VARCHAR(255)"
);

CREATE TABLE "BANK_ACCOUNT_CATEGORY" (
  "id" integer PRIMARY KEY,
  "category" varchar
);

CREATE TABLE "BANK" (
  "id" integer PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "BANK_ACCOUNT" (
  "id_account_category" integer NOT NULL,
  "id_bank" integer NOT NULL,
  "name_recipient" varchar,
  "account_number" varchar,
  PRIMARY KEY ("id_account_category", "id_bank")
);

CREATE TABLE "BRANCH" (
  "id" integer PRIMARY KEY,
  "address" varchar,
  "branch_name" varchar
);

CREATE TABLE "organisasi" (
  "organisasi_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nama_organisasi" varchar(255)
);

CREATE TABLE "auditor" (
  "auditor_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nama_auditor" varchar(255)
);

CREATE TABLE "status_audit" (
  "status_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nama_status" varchar(50)
);

CREATE TABLE "laporan_audit" (
  "laporan_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tahun_audit" int,
  "nama_laporan" varchar(255),
  "status_id" int,
  "auditor_id" int,
  "organisasi_id" int
);

CREATE TABLE "dokumen_laporan" (
  "dokumen_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "laporan_id" int,
  "jenis_dokumen" varchar(100),
  "link_dokumen" text
);

COMMENT ON TABLE "program_partner" IS 'many-to-many relationship between donation_program and partner';

COMMENT ON TABLE "program_article" IS 'optional: link article to a specific donation program';

COMMENT ON TABLE "status_audit" IS 'Status: Selesai, Dalam Proses, Belum Dimulai';

COMMENT ON TABLE "laporan_audit" IS 'Tabel utama laporan audit';

COMMENT ON TABLE "dokumen_laporan" IS 'Jenis: Lihat Laporan, Download Laporan';

ALTER TABLE "donasi" ADD FOREIGN KEY ("kategori") REFERENCES "program" ("id");

ALTER TABLE "donasi_relasi" ADD FOREIGN KEY ("program_id") REFERENCES "donasi" ("id");

ALTER TABLE "donasi_relasi" ADD FOREIGN KEY ("donatur_id") REFERENCES "donatur" ("id");

ALTER TABLE "histori" ADD FOREIGN KEY ("donatur_id") REFERENCES "donatur" ("id");

ALTER TABLE "donation" ADD FOREIGN KEY ("campaign_id") REFERENCES "program" ("id");

ALTER TABLE "donation" ADD FOREIGN KEY ("donor_id") REFERENCES "donor" ("id");

ALTER TABLE "donor" ADD FOREIGN KEY ("id") REFERENCES "history" ("id");

ALTER TABLE "zakat_campaigns" ADD FOREIGN KEY ("category") REFERENCES "program" ("id");

ALTER TABLE "donations" ADD FOREIGN KEY ("campaign_id") REFERENCES "zakat_campaigns" ("id");

ALTER TABLE "donations" ADD FOREIGN KEY ("donor_id") REFERENCES "donors" ("id");

ALTER TABLE "donation_history" ADD FOREIGN KEY ("campaign_id") REFERENCES "zakat_campaigns" ("id");

ALTER TABLE "program_partner" ADD FOREIGN KEY ("program_id") REFERENCES "donation_program" ("id");

ALTER TABLE "program_partner" ADD FOREIGN KEY ("partner_id") REFERENCES "partner" ("id");

ALTER TABLE "article" ADD FOREIGN KEY ("category_id") REFERENCES "article_category" ("id");

ALTER TABLE "program_article" ADD FOREIGN KEY ("program_id") REFERENCES "donation_program" ("id");

ALTER TABLE "program_article" ADD FOREIGN KEY ("article_id") REFERENCES "article" ("id");

ALTER TABLE "testimonial" ADD FOREIGN KEY ("type_id") REFERENCES "testimonial_type" ("id");

ALTER TABLE "testimonial" ADD FOREIGN KEY ("program_id") REFERENCES "testimonial_program" ("id");

ALTER TABLE "qurban_target" ADD FOREIGN KEY ("program_id") REFERENCES "qurban_program" ("id");

ALTER TABLE "qurban_stats" ADD FOREIGN KEY ("program_id") REFERENCES "qurban_program" ("id");

ALTER TABLE "qurban_gallery" ADD FOREIGN KEY ("program_id") REFERENCES "qurban_program" ("id");

ALTER TABLE "BANK_ACCOUNT" ADD FOREIGN KEY ("id_account_category") REFERENCES "BANK_ACCOUNT_CATEGORY" ("id");

ALTER TABLE "BANK_ACCOUNT" ADD FOREIGN KEY ("id_bank") REFERENCES "BANK" ("id");

ALTER TABLE "laporan_audit" ADD FOREIGN KEY ("organisasi_id") REFERENCES "organisasi" ("organisasi_id");

ALTER TABLE "laporan_audit" ADD FOREIGN KEY ("auditor_id") REFERENCES "auditor" ("auditor_id");

ALTER TABLE "laporan_audit" ADD FOREIGN KEY ("status_id") REFERENCES "status_audit" ("status_id");

ALTER TABLE "dokumen_laporan" ADD FOREIGN KEY ("laporan_id") REFERENCES "laporan_audit" ("laporan_id");